KINECT STATS GENERATOR FOR SPORTS VISUALISATION: ExtendedQMdiSubWindow Class Reference
ExtendedQMdiSubWindow Class Reference
#include <ExtendedQMdiSubWindow.h>
Public Member Functions
ExtendedQMdiSubWindow (MainWindow *_parent=0)
Protected Member Functions
void closeEvent (QCloseEvent *closeEvent)
Private Attributes
MainWindow * m_ptrToMainWindow
Detailed Description
Definition at line 15 of file ExtendedQMdiSubWindow.h.
Constructor & Destructor Documentation
ExtendedQMdiSubWindow::ExtendedQMdiSubWindow (MainWindow * _parent = 0)
Definition at line 10 of file ExtendedQMdiSubWindow.cpp.
References m_ptrToMainWindow.
{
    m_ptrToMainWindow = _parent;
}
Member Function Documentation
void ExtendedQMdiSubWindow::closeEvent (QCloseEvent * closeEvent) [protected]
Definition at line 15 of file ExtendedQMdiSubWindow.cpp.
References MainWindow::deleteCurrentDepthvz(), MainWindow::deleteCurrentRGBvz(), MainWindow::deleteCurrentStatsvz(), MainWindow::deleteCurrentTrackingvz(), depthWindowName, m_ptrToMainWindow, rgbWindowName, statsWindowName, and trackingWindowName.
{
    std::cout<<"closing..";
    std::cout<<this->accessibleName().toStdString();
    if(this->accessibleName().toStdString() == statsWindowName)
    {
        m_ptrToMainWindow->deleteCurrentStatsvz();
        std::cout<<"statsclosed";
    }
    if(this->accessibleName().toStdString() == trackingWindowName)
    {
        m_ptrToMainWindow->deleteCurrentTrackingvz();
        std::cout<<"trakingvzclosed";
    }
    if(this->accessibleName().toStdString() == rgbWindowName)
    {
        m_ptrToMainWindow->deleteCurrentRGBvz();
        std::cout<<"rgbclosed";
    }
    if(this->accessibleName().toStdString() == depthWindowName)
    {
        m_ptrToMainWindow->deleteCurrentDepthvz();
        std::cout<<"depthclosed";
    }
    //emit closed( this->objectName() );
    closeEvent->accept();
}
Member Data Documentation
MainWindow* ExtendedQMdiSubWindow::m_ptrToMainWindow [private]
Definition at line 28 of file ExtendedQMdiSubWindow.h.
The documentation for this class was generated from the following files:
ExtendedQMdiSubWindow.h
ExtendedQMdiSubWindow.cpp