KINECT STATS GENERATOR FOR SPORTS VISUALISATION: PlayerData Class Reference
PlayerData Class Reference
contains all statistics mapped to players
#include <PlayerData.h>
Public Member Functions
PlayerData ()
~PlayerData ()
void setPlayerBallPts (std::vector< std::vector< cv::Point3f > > &_inputPointSetsInWorld)
void setPlayerImpactPtIndices (std::vector< std::vector< int > > &_inputDepthIndices)
void setPlayerDataProcessedFlag ()
std::vector< cv::Point > & getPlayerImpactPtsAllRallies ()
std::vector< std::vector
< cv::Point3f > > & getPlayerBallPtsAll ()
std::vector< std::vector< int > > & getPlayerImpactPtIndices ()
float getPercentageDistributionData (int _width, int _height, WHICH_QUADRANT _whichQuadrant)
std::vector< cv::Point > & getQuadSpecificPoints (WHICH_QUADRANT _whichQuad)
std::vector< cv::Point3f > & getBarGraphVertices (cv::Point _inputTopXY, int _width, int _height, int _gridResolution)
std::vector< std::vector
< cv::Point3f > > & getPlayerInterpolatedBallPtsAll (float _inputDistanceFrmKinectToPlayArea)
std::vector< cv::Point3f > & getPlayerImpactPtsIn3DAllRallies ()
std::vector< float > & getPlayerSpeedData (float _inputDistanceFrmKinectToPlayArea)
std::vector< float > & getRevolutionsPerMinute (float _inputDiameterInMeters, float _inputDistanceFrmKinectToPlayArea)
bool checkDataProcessed ()
Private Member Functions
void calculatePlayerImpactPtsFromIndices ()
Private Attributes
TwoDStatsGeneration * m_twoDStatsGenerator
ThreeDStatsGeneration * m_threeDStatsGenerator
bool m_dataProcessed
std::vector< std::vector
< cv::Point3f > > m_playerBallPts
std::vector< std::vector< int > > m_playerDeepestPtIndices
std::vector< cv::Point > m_playerImpactPtsAllRallies
std::vector< cv::Point3f > m_playerImpactPtsAllRalliesIn3D
float m_bottomLeftPercentage
float m_topLeftPercentage
float m_topRightPercentage
float m_bottomRightPercentage
std::vector< cv::Point > m_playerImpactPtsBottomLeft
std::vector< cv::Point > m_playerImpactPtsTopLeft
std::vector< cv::Point > m_playerImpactPtsTopRight
std::vector< cv::Point > m_playerImpactPtsBottomRight
std::vector< cv::Point3f > m_barGraphVertices
std::vector< std::vector
< cv::Point3f > > m_playerInterpolatedBallPts
std::vector< float > m_speedData
std::vector< float > m_rpmData
Detailed Description
contains all statistics mapped to players
Definition at line 26 of file PlayerData.h.
Constructor & Destructor Documentation
PlayerData::PlayerData ()
Definition at line 6 of file PlayerData.cpp.
References m_barGraphVertices, m_bottomLeftPercentage, m_bottomRightPercentage, m_dataProcessed, m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRallies, m_playerImpactPtsAllRalliesIn3D, m_playerImpactPtsBottomLeft, m_playerImpactPtsBottomRight, m_playerImpactPtsTopLeft, m_playerImpactPtsTopRight, m_playerInterpolatedBallPts, m_rpmData, m_speedData, m_threeDStatsGenerator, m_topLeftPercentage, m_topRightPercentage, and m_twoDStatsGenerator.
{
    m_playerBallPts.clear();
    m_playerDeepestPtIndices.clear();
    m_playerImpactPtsAllRallies.clear();
    m_playerImpactPtsAllRalliesIn3D.clear();
    m_playerImpactPtsBottomLeft.clear();
    m_playerImpactPtsTopLeft.clear();
    m_playerImpactPtsTopRight.clear();
    m_playerImpactPtsBottomRight.clear();
    m_barGraphVertices.clear();
    m_playerInterpolatedBallPts.clear();
    m_speedData.clear();
    m_dataProcessed = false;
    m_bottomLeftPercentage = m_topLeftPercentage = 0;
    m_topRightPercentage = m_bottomRightPercentage = 0;
    m_rpmData.clear();
    m_twoDStatsGenerator = new TwoDStatsGeneration();
    m_threeDStatsGenerator = new ThreeDStatsGeneration();
}
PlayerData::~PlayerData ()
Definition at line 31 of file PlayerData.cpp.
References m_barGraphVertices, m_dataProcessed, m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRallies, m_playerImpactPtsAllRalliesIn3D, m_playerImpactPtsBottomLeft, m_playerImpactPtsBottomRight, m_playerImpactPtsTopLeft, m_playerImpactPtsTopRight, m_playerInterpolatedBallPts, m_rpmData, m_speedData, m_threeDStatsGenerator, and m_twoDStatsGenerator.
{
    m_playerBallPts.clear();
    m_playerDeepestPtIndices.clear();
    m_playerImpactPtsAllRallies.clear();
    m_playerImpactPtsAllRalliesIn3D.clear();
    m_playerImpactPtsBottomLeft.clear();
    m_playerImpactPtsTopLeft.clear();
    m_playerImpactPtsTopRight.clear();
    m_playerImpactPtsBottomRight.clear();
    m_barGraphVertices.clear();
    m_playerInterpolatedBallPts.clear();
    m_speedData.clear();
    m_rpmData.clear();
    m_dataProcessed = false;
    delete m_twoDStatsGenerator;
    delete m_threeDStatsGenerator;
}
Member Function Documentation
void PlayerData::calculatePlayerImpactPtsFromIndices () [private]
bool PlayerData::checkDataProcessed ()
Definition at line 296 of file PlayerData.cpp.
References m_dataProcessed.
{
    return m_dataProcessed;
}
std::vector< cv::Point3f > & PlayerData::getBarGraphVertices (cv::Point _inputTopXY, int _width, int _height, int _gridResolution)
Definition at line 177 of file PlayerData.cpp.
References TwoDStatsGeneration::calculatePlayerImpactPtsFromIndices(), ThreeDStatsGeneration::generatePitchDensityGraphData(), m_barGraphVertices, m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRallies, m_threeDStatsGenerator, and m_twoDStatsGenerator.
{
    if(m_barGraphVertices.size() != 0)
    {
        return m_barGraphVertices;
    }
    else
    {
        // call calculate if rally points empty
        if(m_playerImpactPtsAllRallies.size() == 0)
        {
            //calculatePlayerImpactPtsFromIndices();
            m_twoDStatsGenerator->calculatePlayerImpactPtsFromIndices(m_playerBallPts,m_playerDeepestPtIndices,
                                                                      m_playerImpactPtsAllRallies);
        }
        m_threeDStatsGenerator->generatePitchDensityGraphData(_inputTopXY,_width,_height,_gridResolution,m_playerImpactPtsAllRallies,
                                                              m_barGraphVertices);
        return m_barGraphVertices;
    }
}
float PlayerData::getPercentageDistributionData (int _width, int _height, WHICH_QUADRANT _whichQuadrant)
Definition at line 99 of file PlayerData.cpp.
References ALL, BOTTOM_LEFT, BOTTOM_RIGHT, TwoDStatsGeneration::calculatePlayerImpactPtsFromIndices(), TwoDStatsGeneration::generatePercentageDistribution(), m_bottomLeftPercentage, m_bottomRightPercentage, m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRallies, m_playerImpactPtsBottomLeft, m_playerImpactPtsBottomRight, m_playerImpactPtsTopLeft, m_playerImpactPtsTopRight, m_topLeftPercentage, m_topRightPercentage, m_twoDStatsGenerator, TOP_LEFT, and TOP_RIGHT.
{
    float tempPercentage = 0.0;
    // call calculate if rally points empty
    if(m_playerImpactPtsAllRallies.size() == 0)
    {
        //calculatePlayerImpactPtsFromIndices();
        m_twoDStatsGenerator->calculatePlayerImpactPtsFromIndices(m_playerBallPts,m_playerDeepestPtIndices,
                                                                  m_playerImpactPtsAllRallies);
    }
    switch(_whichQuadrant)
    {
        case BOTTOM_LEFT:
        {
            m_twoDStatsGenerator->generatePercentageDistribution(_width,_height,m_playerImpactPtsAllRallies,BOTTOM_LEFT,
                                                                 m_playerImpactPtsBottomLeft,m_bottomLeftPercentage);
            tempPercentage = m_bottomLeftPercentage;
            break;
        }
        case TOP_LEFT:
        {
            m_twoDStatsGenerator->generatePercentageDistribution(_width,_height,m_playerImpactPtsAllRallies,TOP_LEFT,
                                                                m_playerImpactPtsTopLeft,m_topLeftPercentage);
            tempPercentage = m_topLeftPercentage;
            break;
        }
        case TOP_RIGHT:
        {
            m_twoDStatsGenerator->generatePercentageDistribution(_width,_height,m_playerImpactPtsAllRallies,TOP_RIGHT,
                                                                m_playerImpactPtsTopRight,m_topRightPercentage);
            tempPercentage = m_topRightPercentage;
            break;
        }
        case BOTTOM_RIGHT:
        {
            m_twoDStatsGenerator->generatePercentageDistribution(_width,_height,m_playerImpactPtsAllRallies,BOTTOM_RIGHT,
                                                                m_playerImpactPtsBottomRight,m_bottomRightPercentage);
            tempPercentage = m_bottomRightPercentage;
            break;
        }
        case ALL:
        {
            // in case data is needed for all quads, caller has to call this function 4 times
            // and save the returning floats separately
            break;
        }
    }
    return tempPercentage;
}
std::vector< std::vector< cv::Point3f > > & PlayerData::getPlayerBallPtsAll ()
Definition at line 62 of file PlayerData.cpp.
References m_playerBallPts.
{
    return m_playerBallPts;
}
std::vector< std::vector< int > > & PlayerData::getPlayerImpactPtIndices ()
Definition at line 67 of file PlayerData.cpp.
References m_playerDeepestPtIndices.
{
    return m_playerDeepestPtIndices;
}
std::vector< cv::Point > & PlayerData::getPlayerImpactPtsAllRallies ()
Definition at line 72 of file PlayerData.cpp.
References TwoDStatsGeneration::calculatePlayerImpactPtsFromIndices(), m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRallies, and m_twoDStatsGenerator.
{
    // we first check if we have already calculated impact points, if so return,
    // else calculate it now
    if(m_playerImpactPtsAllRallies.size() != 0)
    {
        return m_playerImpactPtsAllRallies;
    }
    else
    {
        //calculatePlayerImpactPtsFromIndices();
        m_twoDStatsGenerator->calculatePlayerImpactPtsFromIndices(m_playerBallPts,m_playerDeepestPtIndices,
                                                                  m_playerImpactPtsAllRallies);
        return m_playerImpactPtsAllRallies;
    }
}
std::vector< cv::Point3f > & PlayerData::getPlayerImpactPtsIn3DAllRallies ()
Definition at line 243 of file PlayerData.cpp.
References ThreeDStatsGeneration::calculatePlayerImpactPtsIn3DFromIndices(), m_playerBallPts, m_playerDeepestPtIndices, m_playerImpactPtsAllRalliesIn3D, and m_threeDStatsGenerator.
{
    if(m_playerImpactPtsAllRalliesIn3D.size() != 0)
    {
        return m_playerImpactPtsAllRalliesIn3D;
    }
    else
    {
        m_threeDStatsGenerator->calculatePlayerImpactPtsIn3DFromIndices(m_playerBallPts,m_playerDeepestPtIndices,
                                                                        m_playerImpactPtsAllRalliesIn3D);
        return m_playerImpactPtsAllRalliesIn3D;
    }
}
std::vector< std::vector< cv::Point3f > > & PlayerData::getPlayerInterpolatedBallPtsAll (float _inputDistanceFrmKinectToPlayArea)
Definition at line 205 of file PlayerData.cpp.
References ThreeDStatsGeneration::generateInterpolatedDataForAllRallies(), m_playerBallPts, m_playerDeepestPtIndices, m_playerInterpolatedBallPts, m_speedData, and m_threeDStatsGenerator.
{
    if(m_playerInterpolatedBallPts.size() != 0)
    {
        return m_playerInterpolatedBallPts;
    }
    else
    {
        m_threeDStatsGenerator->generateInterpolatedDataForAllRallies(m_playerBallPts,m_playerDeepestPtIndices,
                                                                      _inputDistanceFrmKinectToPlayArea,
                                                                      m_playerInterpolatedBallPts,m_speedData);
       // m_threeDStatsGenerator->generateInterpolatedDataForAllRalliesWithoutImpact(m_playerBallPts,m_playerInterpolatedBallPts);
        return m_playerInterpolatedBallPts;
    }
}
std::vector< float > & PlayerData::getPlayerSpeedData (float _inputDistanceFrmKinectToPlayArea)
Definition at line 224 of file PlayerData.cpp.
References ThreeDStatsGeneration::generateInterpolatedDataForAllRallies(), m_playerBallPts, m_playerDeepestPtIndices, m_playerInterpolatedBallPts, m_speedData, and m_threeDStatsGenerator.
{
    // this will be available only when interpolatedballpts function is called
    // as that is where speed data is filled
    //so if interpolatedballpts vec is empty, call the getinterpballpts function
    // and then check if speed data not empty and then return the speeddata vec
    if(m_playerInterpolatedBallPts.size() == 0)
    {
        m_threeDStatsGenerator->generateInterpolatedDataForAllRallies(m_playerBallPts,m_playerDeepestPtIndices,
                                                                      _inputDistanceFrmKinectToPlayArea,
                                                                      m_playerInterpolatedBallPts,m_speedData);
    }
    //if(m_speedData.size() != 0)
    {
        return m_speedData;
    }
}
std::vector< cv::Point > & PlayerData::getQuadSpecificPoints (WHICH_QUADRANT _whichQuad)
Definition at line 156 of file PlayerData.cpp.
References BOTTOM_LEFT, BOTTOM_RIGHT, m_playerImpactPtsBottomLeft, m_playerImpactPtsBottomRight, m_playerImpactPtsTopLeft, m_playerImpactPtsTopRight, TOP_LEFT, and TOP_RIGHT.
{
    if(_whichQuad == BOTTOM_LEFT)
    {
        return m_playerImpactPtsBottomLeft;
    }
    else if(_whichQuad == TOP_LEFT)
    {
        return m_playerImpactPtsTopLeft;
    }
    else if(_whichQuad == TOP_RIGHT)
    {
        return m_playerImpactPtsTopRight;
    }
    else if(_whichQuad == BOTTOM_RIGHT)
    {
        return m_playerImpactPtsBottomRight;
    }
}
std::vector< float > & PlayerData::getRevolutionsPerMinute (float _inputDiameterInMeters, float _inputDistanceFrmKinectToPlayArea)
Definition at line 257 of file PlayerData.cpp.
References ThreeDStatsGeneration::generateInterpolatedDataForAllRallies(), m_playerBallPts, m_playerDeepestPtIndices, m_playerInterpolatedBallPts, m_rpmData, m_speedData, and m_threeDStatsGenerator.
{
    // this make sures speed data is generated first
    // which would then feed into rpm calculations
    if(m_playerInterpolatedBallPts.size() == 0)
    {
        m_threeDStatsGenerator->generateInterpolatedDataForAllRallies(m_playerBallPts,m_playerDeepestPtIndices,
                                                                      _inputDistanceFrmKinectToPlayArea,
                                                                      m_playerInterpolatedBallPts,m_speedData);
    }
    if(m_rpmData.size() != 0)
    {
       return m_rpmData;
    }
    else
    {
        for(int i=0;i<m_speedData.size();i++)
        {
            // this produces revolutions per minute
            // input diameter and speed data are in meters scale
            float tempRPM = (m_speedData[i] * 60)/(3.14 * _inputDiameterInMeters);
            std::cout<<"repm calculated:"<<tempRPM<<"\n";
            m_rpmData.push_back(tempRPM);
        }
        return m_rpmData;
    }
}
void PlayerData::setPlayerBallPts (std::vector< std::vector< cv::Point3f > > & _inputPointSetsInWorld)
Definition at line 52 of file PlayerData.cpp.
References m_playerBallPts.
{
    m_playerBallPts = _inputPointSetsInWorld;
}
void PlayerData::setPlayerDataProcessedFlag ()
Definition at line 291 of file PlayerData.cpp.
References m_dataProcessed.
{
    m_dataProcessed = true;
}
void PlayerData::setPlayerImpactPtIndices (std::vector< std::vector< int > > & _inputDepthIndices)
Definition at line 57 of file PlayerData.cpp.
References m_playerDeepestPtIndices.
{
    m_playerDeepestPtIndices = _inputDepthIndices;
}
Member Data Documentation
std::vector<cv::Point3f> PlayerData::m_barGraphVertices [private]
Definition at line 98 of file PlayerData.h.
float PlayerData::m_bottomLeftPercentage [private]
Definition at line 88 of file PlayerData.h.
float PlayerData::m_bottomRightPercentage [private]
Definition at line 89 of file PlayerData.h.
bool PlayerData::m_dataProcessed [private]
Definition at line 74 of file PlayerData.h.
std::vector<std::vector<cv::Point3f> > PlayerData::m_playerBallPts [private]
Definition at line 77 of file PlayerData.h.
std::vector<std::vector<int> > PlayerData::m_playerDeepestPtIndices [private]
Definition at line 81 of file PlayerData.h.
std::vector<cv::Point> PlayerData::m_playerImpactPtsAllRallies [private]
Definition at line 84 of file PlayerData.h.
std::vector<cv::Point3f> PlayerData::m_playerImpactPtsAllRalliesIn3D [private]
Definition at line 85 of file PlayerData.h.
std::vector<cv::Point> PlayerData::m_playerImpactPtsBottomLeft [private]
Definition at line 94 of file PlayerData.h.
std::vector<cv::Point> PlayerData::m_playerImpactPtsBottomRight [private]
Definition at line 95 of file PlayerData.h.
std::vector<cv::Point> PlayerData::m_playerImpactPtsTopLeft [private]
Definition at line 94 of file PlayerData.h.
std::vector<cv::Point> PlayerData::m_playerImpactPtsTopRight [private]
Definition at line 95 of file PlayerData.h.
std::vector<std::vector<cv::Point3f> > PlayerData::m_playerInterpolatedBallPts [private]
Definition at line 106 of file PlayerData.h.
std::vector<float> PlayerData::m_rpmData [private]
Definition at line 113 of file PlayerData.h.
std::vector<float> PlayerData::m_speedData [private]
Definition at line 111 of file PlayerData.h.
ThreeDStatsGeneration* PlayerData::m_threeDStatsGenerator [private]
Definition at line 64 of file PlayerData.h.
float PlayerData::m_topLeftPercentage [private]
Definition at line 88 of file PlayerData.h.
float PlayerData::m_topRightPercentage [private]
Definition at line 88 of file PlayerData.h.
TwoDStatsGeneration* PlayerData::m_twoDStatsGenerator [private]
Definition at line 63 of file PlayerData.h.
The documentation for this class was generated from the following files:
PlayerData.h
PlayerData.cpp