KINECT STATS GENERATOR FOR SPORTS VISUALISATION: DepthDebugVisualization Class Reference
DepthDebugVisualization Class Reference
to visualize depth data
#include <DepthDebugVisualization.h>
Public Member Functions
DepthDebugVisualization (QWidget *_parent)
Constructor for DepthDebugVisualization.
~DepthDebugVisualization ()
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void timerEvent (QTimerEvent *_event)
called when the timer is triggered
Private Attributes
cv::Mat m_depth
QTime m_timer
ScreenQuad * m_screen
Detailed Description
to visualize depth data
Definition at line 22 of file DepthDebugVisualization.h.
Constructor & Destructor Documentation
DepthDebugVisualization::DepthDebugVisualization (QWidget * _parent)
Constructor for DepthDebugVisualization.
Parameters:
[in] _parent the parent window to create the GL context in
Definition at line 14 of file DepthDebugVisualization.cpp.
References m_depth.
                                                                 : QGLWidget( new CreateCoreGLContext(QGLFormat::defaultFormat()), _parent )
{
  // set this widget to have the initial keyboard focus
 // setFocus();
  // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
  this->resize(_parent->size());
  startTimer(20);
  m_depth = cvCreateMat(480,640,CV_8UC1);
}
DepthDebugVisualization::~DepthDebugVisualization ()
Definition at line 124 of file DepthDebugVisualization.cpp.
References m_screen.
{
    if(m_screen)
    {
        delete m_screen;
    }
}
Member Function Documentation
void DepthDebugVisualization::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
Definition at line 32 of file DepthDebugVisualization.cpp.
References m_screen, and ScreenQuad::setTextureMode().
{
  //
  ngl::NGLInit *Init = ngl::NGLInit::instance();
  Init->initGlew();
  // now we have valid GL can create shaders etc
  ngl::ShaderLib *shader = ngl::ShaderLib::instance();
  shader->createShaderProgram("TextureDepth");
  shader->attachShader("TextureVertex",ngl::VERTEX);
  shader->attachShader("TextureFragment",ngl::FRAGMENT);
  shader->loadShaderSource("TextureVertex","shaders/TextureVert.glsl");
  shader->loadShaderSource("TextureFragment","shaders/LumFrag.glsl");
  shader->compileShader("TextureVertex");
  shader->compileShader("TextureFragment");
  shader->attachShaderToProgram("TextureDepth","TextureVertex");
  shader->attachShaderToProgram("TextureDepth","TextureFragment");
  shader->linkProgramObject("TextureDepth");
  (*shader)["TextureDepth"]->use();
  shader->setShaderParam1i("tex",0);
  m_screen = new ScreenQuad(640,480,"TextureDepth");
  // set this to draw depth textures
  m_screen->setTextureMode(GL_DEPTH_COMPONENT );
  //frame rate GUNDU
  //m_text=new ngl::Text(QFont("Arial",14));
  //currentTime = currentTime.currentTime();
}
void DepthDebugVisualization::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters:
_event the Qt Event structure
Definition at line 94 of file DepthDebugVisualization.cpp.
{
    Q_UNUSED(_event);
}
void DepthDebugVisualization::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 101 of file DepthDebugVisualization.cpp.
{
    Q_UNUSED(_event);
}
void DepthDebugVisualization::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 108 of file DepthDebugVisualization.cpp.
{
  // this event is called when the mouse button is released
  // we then set Rotate to false
  Q_UNUSED(_event);
}
void DepthDebugVisualization::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to
Definition at line 81 of file DepthDebugVisualization.cpp.
References ScreenQuad::draw(), KinectInterface::getDepthSliced(), KinectInterface::instance(), m_depth, and m_screen.
{
    //int temp = 0;
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    KinectInterface *kinect=KinectInterface::instance();
    // this is the raw data will need to be processed
    kinect->getDepthSliced(m_depth);
    m_screen->draw(&m_depth);
}
void DepthDebugVisualization::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
Parameters:
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 68 of file DepthDebugVisualization.cpp.
{
  glViewport(0,0,_w,_h);
  //m_text->setScreenSize(_w,_h);
}
void DepthDebugVisualization::timerEvent (QTimerEvent * _event) [private]
called when the timer is triggered
Definition at line 116 of file DepthDebugVisualization.cpp.
{
    Q_UNUSED(_event);
    // re-draw GL
    updateGL();
}
Member Data Documentation
cv::Mat DepthDebugVisualization::m_depth [private]
Definition at line 36 of file DepthDebugVisualization.h.
ScreenQuad* DepthDebugVisualization::m_screen [private]
Definition at line 40 of file DepthDebugVisualization.h.
QTime DepthDebugVisualization::m_timer [private]
Definition at line 38 of file DepthDebugVisualization.h.
The documentation for this class was generated from the following files:
DepthDebugVisualization.h
DepthDebugVisualization.cpp