KINECT STATS GENERATOR FOR SPORTS VISUALISATION: QuadCurveFitUtility Class Reference
QuadCurveFitUtility Class Reference
#include <QuadCurveFitUtility.h>
Public Member Functions
QuadCurveFitUtility ()
~QuadCurveFitUtility ()
std::vector< cv::Point2f > & getInterPolPts ()
void addPoints (cv::Point2f _inputSet)
void processPoints ()
void processParametricPoints (std::vector< float > &_inputBuffer)
void processParametricPoints3D (std::vector< float > &_inputBuffer, float &o_coeffX)
double getATerm ()
double getBTerm ()
double getCTerm ()
double getRSquare ()
Protected Member Functions
double getSxy (int _nX, int _nY)
double getYMean ()
double getSStot ()
double getSSerr ()
double getPredictedY (double _x)
void calculateHermiteCurvePts (cv::Point3f _startPt, cv::Point3f _endPt, cv::Point3f _startTangent, cv::Point3f _endTangent, float _inputInit, float _interval)
std::vector< cv::Vec4d > splinterp (std::vector< float > x)
double getDifferential (double _x)
Protected Attributes
std::vector< cv::Point2f > m_dataPoints
std::vector< cv::Point2f > m_dataPointsAfterInterpol
std::vector< cv::Point3f > m_hermiteInterPolPts
std::vector< cv::Point3f > m_dataPointsHermite
double m_a
double m_b
double m_c
float m_steps
int m_noOfPoints
Detailed Description
Definition at line 13 of file QuadCurveFitUtility.h.
Constructor & Destructor Documentation
QuadCurveFitUtility::QuadCurveFitUtility ()
Definition at line 13 of file QuadCurveFitUtility.cpp.
References m_a, m_b, m_c, m_dataPoints, m_dataPointsAfterInterpol, m_dataPointsHermite, m_hermiteInterPolPts, m_noOfPoints, and m_steps.
{
    m_dataPoints.clear();
    m_dataPointsAfterInterpol.clear();
    m_hermiteInterPolPts.clear();
    m_dataPointsHermite.clear();
    m_a = m_b = m_c = 0;
    m_steps = 0;
    m_noOfPoints = 5;
}
QuadCurveFitUtility::~QuadCurveFitUtility ()
Definition at line 24 of file QuadCurveFitUtility.cpp.
{
}
Member Function Documentation
void QuadCurveFitUtility::addPoints (cv::Point2f _inputSet)
Definition at line 36 of file QuadCurveFitUtility.cpp.
References m_dataPoints.
{
    m_dataPoints.push_back(_inputSet);
}
void QuadCurveFitUtility::calculateHermiteCurvePts (cv::Point3f _startPt, cv::Point3f _endPt, cv::Point3f _startTangent, cv::Point3f _endTangent, float _inputInit, float _interval) [protected]
double QuadCurveFitUtility::getATerm ()
Definition at line 91 of file QuadCurveFitUtility.cpp.
References getSxy(), m_a, m_dataPoints, and MIN_VALUES.
{
    if( m_dataPoints.size() < MIN_VALUES )
    {
        std::cout<<"Atleast 3 data sets required to interpolate" ;
        return 0;
    }
    // notation sjk to mean the sum of x_i^j_i^k.
    double s40 = getSxy( 4, 0 );
    double s30 = getSxy( 3, 0 );
    double s20 = getSxy( 2, 0 );
    double s10 = getSxy( 1, 0 );
    double s00 = (double)m_dataPoints.size();
    double s21 = getSxy( 2, 1 );
    double s11 = getSxy( 1, 1 );
    double s01 = getSxy( 0, 1 );
    // Da / D
    m_a = (s21 * (s20 * s00 - s10 * s10) - s11 * (s30 * s00 - s10 * s20) + s01 * (s30 * s10 - s20 * s20))
                /
                (s40 * (s20 * s00 - s10 * s10) - s30 * (s30 * s00 - s10 * s20) + s20 * (s30 * s10 - s20 * s20));
    return m_a;
}
double QuadCurveFitUtility::getBTerm ()
Definition at line 125 of file QuadCurveFitUtility.cpp.
References getSxy(), m_b, m_dataPoints, and MIN_VALUES.
{
    if( m_dataPoints.size() < MIN_VALUES )
    {
        std::cout<<"Atleast 3 data sets required to interpolate" ;
        return 0;
    }
    // notation sjk to mean the sum of x_i^j_i^k.
    double s40 = getSxy( 4, 0 );
    double s30 = getSxy( 3, 0 );
    double s20 = getSxy( 2, 0 );
    double s10 = getSxy( 1, 0 );
    double s00 = (double)m_dataPoints.size();
    double s21 = getSxy( 2, 1 );
    double s11 = getSxy( 1, 1 );
    double s01 = getSxy( 0, 1 );
    //   Db / D
    m_b = (s40 * (s11 * s00 - s01 * s10) - s30 * (s21 * s00 - s01 * s20) + s20 * (s21 * s10 - s11 * s20))
        /
        (s40 * (s20 * s00 - s10 * s10) - s30 * (s30 * s00 - s10 * s20) + s20 * (s30 * s10 - s20 * s20));
    return m_b;
}
double QuadCurveFitUtility::getCTerm ()
Definition at line 160 of file QuadCurveFitUtility.cpp.
References getSxy(), m_c, m_dataPoints, and MIN_VALUES.
{
    if( m_dataPoints.size() < MIN_VALUES )
    {
        std::cout<<"Atleast 3 data sets required to interpolate" ;
        return 0;
    }
    // notation sjk to mean the sum of x_i^j_i^k.
    double s40 = getSxy( 4, 0 );
    double s30 = getSxy( 3, 0 );
    double s20 = getSxy( 2, 0 );
    double s10 = getSxy( 1, 0 );
    double s00 = (double)m_dataPoints.size();
    double s21 = getSxy( 2, 1 );
    double s11 = getSxy( 1, 1 );
    double s01 = getSxy( 0, 1 );
    //   Dc / D
    m_c = (s40*(s20 * s01 - s10 * s11) - s30*(s30 * s01 - s10 * s21) + s20*(s30 * s11 - s20 * s21))
            /
            (s40 * (s20 * s00 - s10 * s10) - s30 * (s30 * s00 - s10 * s20) + s20 * (s30 * s10 - s20 * s20));
    return m_c;
}
double QuadCurveFitUtility::getDifferential (double _x) [protected]
Definition at line 306 of file QuadCurveFitUtility.cpp.
References getATerm(), and getBTerm().
{
    //2at + b is the differential
    return ((2 * getATerm() *  _x) + (getBTerm()));
}
std::vector<cv::Point2f>& QuadCurveFitUtility::getInterPolPts ()
double QuadCurveFitUtility::getPredictedY (double _x) [protected]
Definition at line 301 of file QuadCurveFitUtility.cpp.
References getATerm(), getBTerm(), and getCTerm().
{
    return (getATerm() * pow( _x, 2 )) + (getBTerm() * _x) + getCTerm();
}
double QuadCurveFitUtility::getRSquare ()
Definition at line 195 of file QuadCurveFitUtility.cpp.
References getSSerr(), getSStot(), m_dataPoints, and MIN_VALUES.
{
    if( m_dataPoints.size() < MIN_VALUES )
    {
        std::cout<<"Atleast 3 data sets required to interpolate" ;
        return 0;
    }
    return (1.0 - getSSerr() / getSStot());
}
double QuadCurveFitUtility::getSSerr () [protected]
Definition at line 278 of file QuadCurveFitUtility.cpp.
References getPredictedY(), and m_dataPoints.
{
    double ssErr = 0.0;
    //auto pThis = this;
    for(int i = 0;i<m_dataPoints.size();i++)
    {
        ssErr += pow( (m_dataPoints[i].y - getPredictedY( m_dataPoints[i].x)), 2 );
    }
    return ssErr;
}
double QuadCurveFitUtility::getSStot () [protected]
Definition at line 258 of file QuadCurveFitUtility.cpp.
References getYMean(), and m_dataPoints.
{
    double ssTot = 0.0;
    double dYMean = getYMean();
    for(int i = 0;i<m_dataPoints.size();i++)
    {
        ssTot += pow( (m_dataPoints[i].y * dYMean), 2 );
    }
    return ssTot;
}
double QuadCurveFitUtility::getSxy (int _nX, int _nY) [protected]
Definition at line 219 of file QuadCurveFitUtility.cpp.
References m_dataPoints.
{
    double dSxy = 0.0;
    for(int i = 0;i<m_dataPoints.size();i++)
    {
        dSxy += pow(m_dataPoints[i].x,_nX) * pow(m_dataPoints[i].y,_nY);
    }
    return dSxy;
}
double QuadCurveFitUtility::getYMean () [protected]
Definition at line 238 of file QuadCurveFitUtility.cpp.
References m_dataPoints.
{
    double dTotal = 0.0;
    int nCount = 0;
    for(int i = 0;i<m_dataPoints.size();i++)
    {
        dTotal += m_dataPoints[i].y;
        nCount++;
    }
    return dTotal / nCount;
}
void QuadCurveFitUtility::processParametricPoints (std::vector< float > & _inputBuffer)
Definition at line 332 of file QuadCurveFitUtility.cpp.
References getPredictedY(), and m_dataPoints.
{
    int i = m_dataPoints.size();
    //std::sort(m_dataPoints)
    std::cout<<"size is:"<<i<<"first:"<<m_dataPoints[0].x<<"::"<<m_dataPoints[0].y<<"last:"<<m_dataPoints[i - 1].x<<"::"<<m_dataPoints[i - 1].y<<"\n";
    double temp = 0;
    if(i != 0)
    {
        temp = m_dataPoints[0].x;
        while(temp <= 1.0)
        {
            std::cout<<" Interpol. X and Y are: "<<temp<<":"<<getPredictedY(temp);
            //m_dataPointsAfterInterpol.push_back(cv::Point2f(temp,getPredictedY(temp)));
            _inputBuffer.push_back(getPredictedY(temp));
            temp = temp + 0.01;
        }
    }
}
void QuadCurveFitUtility::processParametricPoints3D (std::vector< float > & _inputBuffer, float & o_coeffX)
Definition at line 353 of file QuadCurveFitUtility.cpp.
References getDifferential(), getPredictedY(), and m_dataPoints.
{
    int i = m_dataPoints.size();
    //std::sort(m_dataPoints)
    std::cout<<"size is:"<<i<<"first:"<<m_dataPoints[0].x<<"::"<<m_dataPoints[0].y<<"last:"<<m_dataPoints[i - 1].x<<"::"<<m_dataPoints[i - 1].y<<"\n";
    double temp = 0;
    if(i != 0)
    {
        temp = m_dataPoints[0].x;
        while(temp <= 1.0)
        {
            std::cout<<" Interpol. X and Y are: "<<temp<<":"<<getPredictedY(temp);
            //m_dataPointsAfterInterpol.push_back(cv::Point2f(temp,getPredictedY(temp)));
            float tempValue = getPredictedY(temp);
            if(!(std::isnan(tempValue)))
            {
                _inputBuffer.push_back(getPredictedY(temp));
            }
            temp = temp + 0.01;
        }
        // get the differential at t = 1.0 which will be our
        // tangent to the impact point
        o_coeffX = getDifferential(1.0);
    }
}
void QuadCurveFitUtility::processPoints ()
Definition at line 312 of file QuadCurveFitUtility.cpp.
References getPredictedY(), m_dataPoints, and m_dataPointsAfterInterpol.
{
    int i = m_dataPoints.size();
    //std::sort(m_dataPoints)
    std::cout<<"size is:"<<i<<"first:"<<m_dataPoints[0].x<<"::"<<m_dataPoints[0].y<<"last:"<<m_dataPoints[i - 1].x<<"::"<<m_dataPoints[i - 1].y<<"\n";
    double temp = 0;
    if(i != 0)
    {
        temp = m_dataPoints[0].x;
        while(temp < m_dataPoints[i - 1].x)
        {
            std::cout<<" Interpol. X and Y are: "<<temp<<":"<<getPredictedY(temp);
            m_dataPointsAfterInterpol.push_back(cv::Point2f(temp,getPredictedY(temp)));
            temp = temp + 0.01;
        }
    }
}
std::vector<cv::Vec4d> QuadCurveFitUtility::splinterp (std::vector< float > x) [protected]
Member Data Documentation
double QuadCurveFitUtility::m_a [protected]
Definition at line 29 of file QuadCurveFitUtility.h.
double QuadCurveFitUtility::m_b [protected]
Definition at line 30 of file QuadCurveFitUtility.h.
double QuadCurveFitUtility::m_c [protected]
Definition at line 31 of file QuadCurveFitUtility.h.
std::vector<cv::Point2f> QuadCurveFitUtility::m_dataPoints [protected]
Definition at line 23 of file QuadCurveFitUtility.h.
std::vector<cv::Point2f> QuadCurveFitUtility::m_dataPointsAfterInterpol [protected]
Definition at line 24 of file QuadCurveFitUtility.h.
std::vector<cv::Point3f> QuadCurveFitUtility::m_dataPointsHermite [protected]
Definition at line 27 of file QuadCurveFitUtility.h.
std::vector<cv::Point3f> QuadCurveFitUtility::m_hermiteInterPolPts [protected]
Definition at line 26 of file QuadCurveFitUtility.h.
int QuadCurveFitUtility::m_noOfPoints [protected]
Definition at line 35 of file QuadCurveFitUtility.h.
float QuadCurveFitUtility::m_steps [protected]
Definition at line 34 of file QuadCurveFitUtility.h.
The documentation for this class was generated from the following files:
QuadCurveFitUtility.h
QuadCurveFitUtility.cpp