KINECT STATS GENERATOR FOR SPORTS VISUALISATION: BallTrackingUtility Class Reference
BallTrackingUtility Class Reference
ball track utility
#include <BallTrackingUtility.h>
Public Slots
void setBinaryLowerThresh (double _lowerThresh)
void setStructuringElementSize (int _size)
void setBlurSize (int _size)
void setCannyLowerThresh (double _lowerThresh)
void setCannyHigherThresh (double _higherThresh)
void setNumerOfDialtions (int _numberOfDialtions)
void setContourAreaThresh (double _contourAreaThresh)
void setDifferenceInAreaThresh (double _diffAreaThresh)
void setMasterRigCheck (int _masterRigCheck)
void trackBall ()
Public Member Functions
BallTrackingUtility ()
Constructor for RGBboundsVisualization.
BallTrackingUtility (BallPointsProcessing *_inputBallProcessingUtility)
~BallTrackingUtility ()
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void timerEvent (QTimerEvent *_event)
called when the timer is triggered
void convertToWorldFromScreen (float _iScreen, float _jScreen, float _zDepth)
void fillparametricCoords ()
Private Attributes
cv::Mat m_rgb
cv::Mat m_gray
cv::Mat m_nextBuffer
cv::Mat m_prevBuffer
cv::Mat m_diffBuffer
cv::Mat m_bufferDepthRaw
cv::Mat m_bufferDepthRaw1
float m_depthinm [640 *480]
QTime m_timer
std::vector< cv::Point3f > m_ballPoints
std::vector< cv::Point3f > m_processedBallPts
std::vector< cv::Point2f > m_pointList
std::vector< cv::Point2f > m_pointListXZ
std::vector< cv::Point2f > m_pointListForCV
std::vector< cv::Moments > m_momentList
QuadCurveFitUtility * m_quadFit
QuadCurveFitUtility * m_quadFitXZ
QuadCurveFitUtility * m_quadFitForCV
QuadCurveFitUtility * m_quadFitHermite
QuadCurveFitUtility * m_quadFitX
QuadCurveFitUtility * m_quadFitY
QuadCurveFitUtility * m_quadFitZ
cv::Mat canny_output
std::vector< std::vector
< cv::Point > > contours
std::vector< int > hull
std::vector< cv::Vec4i > defects
std::vector< cv::Vec4i > hierarchy
double area
double rectArea
std::vector< cv::Moments > mu
std::vector< cv::Point2f > mc
double m_binaryLowerThresh
double m_binaryMaxVal
double m_cannyLowerThresh
double m_cannyHigherThresh
double m_contourAreaThresh
double m_diffAreaThresh
int m_ellipsesize
int m_blurSize
int m_noOfTimesToDialate
int m_masterRigCheck
std::vector< cv::Point2f > m_playerAImpactData
QTimer * m_updateTimer
BallPointsProcessing * m_ballPointProcessing
Detailed Description
ball track utility
Definition at line 24 of file BallTrackingUtility.h.
Constructor & Destructor Documentation
BallTrackingUtility::BallTrackingUtility ()
Constructor for RGBboundsVisualization.
Parameters:
[in] _parent the parent window to create the GL context in
Definition at line 24 of file BallTrackingUtility.cpp.
{
}
BallTrackingUtility::BallTrackingUtility (BallPointsProcessing * _inputBallProcessingUtility)
Definition at line 30 of file BallTrackingUtility.cpp.
References area, m_ballPoints, m_binaryLowerThresh, m_binaryMaxVal, m_blurSize, m_bufferDepthRaw, m_bufferDepthRaw1, m_cannyHigherThresh, m_cannyLowerThresh, m_contourAreaThresh, m_depthinm, m_diffAreaThresh, m_diffBuffer, m_ellipsesize, m_gray, m_masterRigCheck, m_momentList, m_nextBuffer, m_noOfTimesToDialate, m_prevBuffer, m_processedBallPts, m_rgb, m_updateTimer, rectArea, and trackBall().
                                                                                         :m_ballPointProcessing(_inputBallProcessingUtility)
{
  m_rgb = cvCreateMat(480,640,CV_8UC3);
  m_gray = cvCreateMat(480,640,CV_8UC1);
  m_nextBuffer = cvCreateMat(480,640,CV_8UC1);
  m_prevBuffer = cvCreateMat(480,640,CV_8UC1);
  m_diffBuffer = cvCreateMat(480,640,CV_8UC1);
  m_bufferDepthRaw=cvCreateMat(480,640,CV_8UC1);
  m_bufferDepthRaw1=cvCreateMat(480,640,CV_8UC1);
  m_binaryLowerThresh = 100.0;
  m_binaryMaxVal = 255.0;
  m_cannyLowerThresh = 100.0;
  m_cannyHigherThresh = 300.0;
  m_contourAreaThresh = 120.0;
  m_diffAreaThresh = 30.0;
  m_ellipsesize = 2;
  m_blurSize = 5;
  m_noOfTimesToDialate = 2;
  m_masterRigCheck = 0;
  for( unsigned int i = 0 ; i < 640*480 ; ++i)
  {
      m_depthinm[i] = 0;
  }
  // all these are separate lists filled by separate calls to interpolate functions
  m_ballPoints.clear();
  m_momentList.clear();
  m_processedBallPts.clear();
  area = rectArea = 0.0;
  m_updateTimer = new QTimer(this);
  connect(m_updateTimer, SIGNAL(timeout()), this, SLOT(trackBall()));
  m_updateTimer->start(1);
}
BallTrackingUtility::~BallTrackingUtility ()
Definition at line 223 of file BallTrackingUtility.cpp.
{
}
Member Function Documentation
void BallTrackingUtility::convertToWorldFromScreen (float _iScreen, float _jScreen, float _zDepth) [private]
Definition at line 210 of file BallTrackingUtility.cpp.
References m_ballPoints.
{
    float x = (_iScreen/640 - 0.5) * _zDepth * 1.111467f;
    float y = (0.5 - _jScreen/480) * _zDepth * 0.833599f;
     m_ballPoints.push_back(cv::Point3f(-(y),(1 - _zDepth),-x));
}
void BallTrackingUtility::fillparametricCoords () [private]
void BallTrackingUtility::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters:
_event the Qt Event structure
Definition at line 178 of file BallTrackingUtility.cpp.
{
    Q_UNUSED(_event);
}
void BallTrackingUtility::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 185 of file BallTrackingUtility.cpp.
{
    Q_UNUSED(_event);
}
void BallTrackingUtility::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 192 of file BallTrackingUtility.cpp.
{
  // this event is called when the mouse button is released
  // we then set Rotate to false
  Q_UNUSED(_event);
}
void BallTrackingUtility::setBinaryLowerThresh (double _lowerThresh) [slot]
Definition at line 231 of file BallTrackingUtility.cpp.
References m_binaryLowerThresh.
{
    m_binaryLowerThresh = _lowerThresh;
    //updateGL();
}
void BallTrackingUtility::setBlurSize (int _size) [slot]
Definition at line 243 of file BallTrackingUtility.cpp.
References m_blurSize.
{
    m_blurSize = _size;
    //updateGL();
}
void BallTrackingUtility::setCannyHigherThresh (double _higherThresh) [slot]
Definition at line 256 of file BallTrackingUtility.cpp.
References m_cannyHigherThresh.
{
    m_cannyHigherThresh = _higherThresh;
    //updateGL();
}
void BallTrackingUtility::setCannyLowerThresh (double _lowerThresh) [slot]
Definition at line 249 of file BallTrackingUtility.cpp.
References m_cannyLowerThresh.
{
    m_cannyLowerThresh = _lowerThresh;
    //updateGL();
}
void BallTrackingUtility::setContourAreaThresh (double _contourAreaThresh) [slot]
Definition at line 269 of file BallTrackingUtility.cpp.
References m_contourAreaThresh.
{
    m_contourAreaThresh = _contourAreaThresh;
    //updateGL();
}
void BallTrackingUtility::setDifferenceInAreaThresh (double _diffAreaThresh) [slot]
Definition at line 275 of file BallTrackingUtility.cpp.
References m_diffAreaThresh.
{
    m_diffAreaThresh = _diffAreaThresh;
    //updateGL();
}
void BallTrackingUtility::setMasterRigCheck (int _masterRigCheck) [slot]
Definition at line 281 of file BallTrackingUtility.cpp.
References m_masterRigCheck.
{
    m_masterRigCheck = _masterRigCheck;
    //updateGL();
}
void BallTrackingUtility::setNumerOfDialtions (int _numberOfDialtions) [slot]
Definition at line 263 of file BallTrackingUtility.cpp.
References m_noOfTimesToDialate.
{
    m_noOfTimesToDialate = _numberOfDialtions;
    //updateGL();
}
void BallTrackingUtility::setStructuringElementSize (int _size) [slot]
Definition at line 237 of file BallTrackingUtility.cpp.
References m_ellipsesize.
{
    m_ellipsesize = _size;
    //updateGL();
}
void BallTrackingUtility::timerEvent (QTimerEvent * _event) [private]
called when the timer is triggered
Definition at line 200 of file BallTrackingUtility.cpp.
References trackBall().
{
    Q_UNUSED(_event);
    // re-draw GL
    //updateGL();
    trackBall();
}
void BallTrackingUtility::trackBall () [slot]
Detect edges using canny
Find contours
Definition at line 79 of file BallTrackingUtility.cpp.
References area, canny_output, contours, convertToWorldFromScreen(), KinectInterface::getBoxObject(), KinectInterface::getDepthRaw(), KinectInterface::getTrackingFlag(), hierarchy, KinectInterface::instance(), m_ballPointProcessing, m_binaryLowerThresh, m_binaryMaxVal, m_blurSize, m_bufferDepthRaw, m_bufferDepthRaw1, m_cannyHigherThresh, m_cannyLowerThresh, m_contourAreaThresh, m_depthinm, m_diffAreaThresh, m_diffBuffer, m_ellipsesize, m_gray, m_momentList, m_nextBuffer, m_noOfTimesToDialate, m_prevBuffer, and BallPointsProcessing::setTrackedPoints().
{
    KinectInterface *kinect=KinectInterface::instance();
    cv::Rect _boundsCheck = kinect->getBoxObject();
 if(kinect->getTrackingFlag())
 {
    static int _frameCount = 1;
    float depth = 0.0;
    kinect->getDepthRaw(m_bufferDepthRaw,m_depthinm);
    cv::blur(m_bufferDepthRaw,m_bufferDepthRaw1,cv::Size(m_blurSize,m_blurSize));
    // to reduce noise, smotthing has been done
    if(_frameCount == 1)
    {
        m_bufferDepthRaw1.copyTo(m_prevBuffer);
    }
    m_bufferDepthRaw1.copyTo(m_nextBuffer);
    cv::absdiff(m_nextBuffer,m_prevBuffer,m_diffBuffer);
    // has gpu variant // bg subtraction by frame differencing ...GMM method seems good through forums if at all we need
    m_nextBuffer.copyTo(m_prevBuffer);
    m_diffBuffer.copyTo(m_gray);
    cv::threshold(m_gray,m_gray,m_binaryLowerThresh,m_binaryMaxVal,CV_THRESH_BINARY_INV);
    cv::Mat element = cv::getStructuringElement(cv::MORPH_ELLIPSE,cv::Size(m_ellipsesize,m_ellipsesize));
    cv::dilate(m_gray,m_gray,element,cv::Point(-1,-1),m_noOfTimesToDialate);
    cv::erode(m_gray,m_gray,element,cv::Point(-1,-1),m_noOfTimesToDialate);
    cv::Canny( m_gray, canny_output, m_cannyLowerThresh, m_cannyHigherThresh, 3 ); // maintiain upper::lower ratio as 2:1 or 3:1 for better results
                                                                                   // as suggested by CANNY
    cv::findContours( canny_output, contours, hierarchy, CV_RETR_LIST, CV_CHAIN_APPROX_SIMPLE, cv::Point(0, 0) ); // methods to be decided
    for( int i = 0; i < contours.size(); i++ )
    {
        /* cv::drawContours( drawing, contours, i, cv::Scalar(255,0,0),-1, 8, hierarchy, 0, cv::Point() );*/ // -- DEV PURPOSE
        area = cv::contourArea(contours[i], false);
        cv::RotatedRect r = cv::minAreaRect(contours[i]);
        if (fabs(area) < m_contourAreaThresh) //my notes: this value is more important in reducing the
            //false positives and filters out those false positives by preventing them
            // from getting processed further..provide in UI
        {
            continue;
        }
        else
        {
            // do nothing
        }
       if (fabs(fabs(area) - (r.size.width * r.size.height * 3.14 / 4)) < m_diffAreaThresh)
       {
           m_momentList.push_back(cv::moments( contours[i], false ));
           float _xMomentsTemp = static_cast<float>(cv::moments( contours[i], false ).m10/cv::moments( contours[i], false ).m00);
           float _yMomentsTemp = static_cast<float>(cv::moments( contours[i], false ).m01/cv::moments( contours[i], false ).m00);
           int depthIndex = (int)((640 - _xMomentsTemp) + (640 * _yMomentsTemp));
           depth = m_depthinm[depthIndex] * 0.001;
           if(depth != 0)
           {
            if((_xMomentsTemp >= _boundsCheck.x) && (_xMomentsTemp <= _boundsCheck.x + _boundsCheck.width) &&
                    (_yMomentsTemp >= _boundsCheck.y) && (_yMomentsTemp <= _boundsCheck.y + _boundsCheck.height))
            {
                std::cout<<"XMoments:"<<_xMomentsTemp<<"\n";
                m_ballPointProcessing->setTrackedPoints(cv::Point3f(_xMomentsTemp,_yMomentsTemp,depth));
                convertToWorldFromScreen(_xMomentsTemp,_yMomentsTemp,depth);
             }
            }
          }
        }
        _frameCount++;
  }
 else
 {
     // tracking not yet started...do nothing
 }
}
Member Data Documentation
double BallTrackingUtility::area [private]
Definition at line 49 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::canny_output [private]
Definition at line 43 of file BallTrackingUtility.h.
std::vector<std::vector<cv::Point> > BallTrackingUtility::contours [private]
Definition at line 44 of file BallTrackingUtility.h.
std::vector<cv::Vec4i> BallTrackingUtility::defects [private]
Definition at line 46 of file BallTrackingUtility.h.
std::vector<cv::Vec4i> BallTrackingUtility::hierarchy [private]
Definition at line 47 of file BallTrackingUtility.h.
std::vector<int> BallTrackingUtility::hull [private]
Definition at line 45 of file BallTrackingUtility.h.
BallPointsProcessing* BallTrackingUtility::m_ballPointProcessing [private]
Definition at line 61 of file BallTrackingUtility.h.
std::vector<cv::Point3f> BallTrackingUtility::m_ballPoints [private]
Definition at line 36 of file BallTrackingUtility.h.
double BallTrackingUtility::m_binaryLowerThresh [private]
Definition at line 54 of file BallTrackingUtility.h.
double BallTrackingUtility::m_binaryMaxVal [private]
Definition at line 54 of file BallTrackingUtility.h.
int BallTrackingUtility::m_blurSize [private]
Definition at line 55 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_bufferDepthRaw [private]
Definition at line 33 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_bufferDepthRaw1 [private]
Definition at line 33 of file BallTrackingUtility.h.
double BallTrackingUtility::m_cannyHigherThresh [private]
Definition at line 54 of file BallTrackingUtility.h.
double BallTrackingUtility::m_cannyLowerThresh [private]
Definition at line 54 of file BallTrackingUtility.h.
double BallTrackingUtility::m_contourAreaThresh [private]
Definition at line 54 of file BallTrackingUtility.h.
float BallTrackingUtility::m_depthinm[640 *480] [private]
Definition at line 34 of file BallTrackingUtility.h.
double BallTrackingUtility::m_diffAreaThresh [private]
Definition at line 54 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_diffBuffer [private]
Definition at line 33 of file BallTrackingUtility.h.
int BallTrackingUtility::m_ellipsesize [private]
Definition at line 55 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_gray [private]
Definition at line 31 of file BallTrackingUtility.h.
int BallTrackingUtility::m_masterRigCheck [private]
Definition at line 55 of file BallTrackingUtility.h.
std::vector<cv::Moments> BallTrackingUtility::m_momentList [private]
Definition at line 38 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_nextBuffer [private]
Definition at line 33 of file BallTrackingUtility.h.
int BallTrackingUtility::m_noOfTimesToDialate [private]
Definition at line 55 of file BallTrackingUtility.h.
std::vector<cv::Point2f> BallTrackingUtility::m_playerAImpactData [private]
Definition at line 57 of file BallTrackingUtility.h.
std::vector<cv::Point2f> BallTrackingUtility::m_pointList [private]
Definition at line 37 of file BallTrackingUtility.h.
std::vector<cv::Point2f> BallTrackingUtility::m_pointListForCV [private]
Definition at line 37 of file BallTrackingUtility.h.
std::vector<cv::Point2f> BallTrackingUtility::m_pointListXZ [private]
Definition at line 37 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_prevBuffer [private]
Definition at line 33 of file BallTrackingUtility.h.
std::vector<cv::Point3f> BallTrackingUtility::m_processedBallPts [private]
Definition at line 36 of file BallTrackingUtility.h.
QuadCurveFitUtility* BallTrackingUtility::m_quadFit [private]
Definition at line 40 of file BallTrackingUtility.h.
QuadCurveFitUtility * BallTrackingUtility::m_quadFitForCV [private]
Definition at line 40 of file BallTrackingUtility.h.
QuadCurveFitUtility * BallTrackingUtility::m_quadFitHermite [private]
Definition at line 40 of file BallTrackingUtility.h.
QuadCurveFitUtility* BallTrackingUtility::m_quadFitX [private]
Definition at line 41 of file BallTrackingUtility.h.
QuadCurveFitUtility * BallTrackingUtility::m_quadFitXZ [private]
Definition at line 40 of file BallTrackingUtility.h.
QuadCurveFitUtility * BallTrackingUtility::m_quadFitY [private]
Definition at line 41 of file BallTrackingUtility.h.
QuadCurveFitUtility * BallTrackingUtility::m_quadFitZ [private]
Definition at line 41 of file BallTrackingUtility.h.
cv::Mat BallTrackingUtility::m_rgb [private]
Definition at line 31 of file BallTrackingUtility.h.
QTime BallTrackingUtility::m_timer [private]
Definition at line 35 of file BallTrackingUtility.h.
QTimer* BallTrackingUtility::m_updateTimer [private]
Definition at line 59 of file BallTrackingUtility.h.
std::vector<cv::Point2f> BallTrackingUtility::mc [private]
Definition at line 52 of file BallTrackingUtility.h.
std::vector<cv::Moments> BallTrackingUtility::mu [private]
Definition at line 51 of file BallTrackingUtility.h.
double BallTrackingUtility::rectArea [private]
Definition at line 49 of file BallTrackingUtility.h.
The documentation for this class was generated from the following files:
BallTrackingUtility.h
BallTrackingUtility.cpp